#!/bin/sh


if [ "$RHO_PLATFORM" = "android" ]; then

cd platform/android
rake --trace

elif [ "$RHO_PLATFORM" = "iphone" ]; then

echo "Performing framework injection in Xcode Project"
chmod +x xcode_mod.sh
./xcode_mod.sh

cd platform/iphone
rake --trace

elif [ "$RHO_PLATFORM" = "osx" ]; then

cd platform/qt
rake --trace

fi
